version: "2.3"

services:
  wine:
    build:
      context: .
      dockerfile: docker/wine.Dockerfile
    # prevent different users from clobbering each others images
    image: ${WINE_DOCKER_REPO}:wine_${WINE_USERNAME}
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${WINE_UID}
      - DOCKER_GIDS=${WINE_GIDS}
      - DOCKER_GROUP_NAMES=${WINE_GROUP_NAMES}
      - DOCKER_USERNAME=user
      - DISPLAY
    # cap_add:
    #   - SYS_PTRACE # Useful for gdb
    volumes:
      - type: bind
        source: ${WINE_SOURCE_DIR}
        target: ${WINE_SOURCE_DIR_DOCKER}
      - type: volume
        target: /home/wine
        source: wine-prefix
volumes:
  wine-prefix:
